const menu = [
    {
        id: 1,
        title: 'Waffles',
        category: 'breakfast',
        price: 200,
        img: './images/p1.jpg',
        desc: `Belgian-style waffles served with a side of your choice`,
    },
    {
        id: 2,
        title: 'French Toast',
        category: 'breakfast',
        price: 180,
        img: './images/p2.jpg',
        desc: `Brioche bread French toast served with a side of your choice`,
    },
    {
        id: 3,
        title: 'Philly Steak Sandwich',
        category: 'Sandwiches',
        price: 270,
        img: './images/p3.jpg',
        desc: `Sandwich made with thinly sliced pieces of fillet steak and melted cheese served on a baguette with French fries`,
    },
    {
        id: 4,
        title: 'Meatball Sandwich',
        category: 'Sandwiches',
        price: 270,
        img: './images/p4.jpg',
        desc: `Italian style spiced meat balls drenched with marinara sauce with melted mozzarella on a baguette with French fries`,
    },
    {
        id: 5,
        title: 'The Umami Burger',
        category: 'Burgers',
        price: 280,
        img: './images/p5.jpg',
        desc: `Double grass-fed meat patties grilled to perfection with tomatoes, onions, pickles, salad, gouda cheese and house sauce on a freshly baked brioche bun with a side of French fries`,
    },
    {
        id: 6,
        title: 'Donut Slider',
        category: 'Burgers',
        price: 230,
        img: './images/p6.jpg',
        desc: `Three pieces of delectable mini-donuts stuffed with mini patties, tomatoes, onions, pickles, salad, mustard and gouda cheese with a side of French fries`,
    },
    {
        id: 7,
        title: 'Lasagna',
        category: 'Pasta',
        price: 250,
        img: './images/p7.jpg',
        desc: `Served with a side of Salad`,
    },
    {
        id: 8,
        title: 'Chicken Alfredo',
        category: 'Pasta',
        price: 280,
        img: './images/p8.jpg',
        desc: `Penne pasta in a creamy sauce with grilled chicken strips and melted mozzarella`,
    },
    {
        id: 9,
        title: 'Grilled Nile Perch',
        category: 'Fish',
        price: 350,
        img: './images/p9.jpg',
        desc: `Served with seasonal veggies and French fries`,
    },
    {
        id: 10,
        title: 'Fish Taco',
        category: 'Fish',
        price: 220,
        img: './images/p10.jpg',
        desc: `Fish taco with red and black beans base, vegan mayo, salsa, shredded cabbage, sweet corn and a side of nacho chips and guacamole`,
    },
    {
        id: 11,
        title: 'Crepes',
        category: 'breakfast',
        price: 180,
        img: './images/p11.jpg',
        desc: `Served with a side of your choice`,
    },
];
export default menu;
